"""rename address

Revision ID: 78f3a9099e18
Revises: e92d5b665e41
Create Date: 2024-03-11 14:47:23.922781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f3a9099e18'
down_revision = 'e92d5b665e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')

    # ### end Alembic commands ###
